"use client";

import { useMemo, useState } from "react";
import { Download, Megaphone, ScanLine, Search, Settings2, ShieldCheck, UsersRound } from "lucide-react";
import type { AdminData } from "@/lib/admin";

export function AdminConsole({ data }: { data: AdminData }) {
  const [query, setQuery] = useState(""); const [university, setUniversity] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const participants = useMemo(() => data.participants.filter((person) => (!query || `${person.name} ${person.email} ${person.code}`.toLowerCase().includes(query.toLowerCase())) && (!university || person.university === university)), [data.participants, query, university]);
  const universities = [...new Set(data.participants.map((person) => person.university))].sort();
  async function command(payload: Record<string, unknown>) {
    setBusy(true); setNotice(""); const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setNotice(response.ok ? "Command applied." : result.error ?? "Command failed."); setBusy(false); if (response.ok) window.location.reload();
  }
  return <div className="admin-shell">
    <header className="admin-header"><div><span className="platform-kicker">CreateX operations</span><h1>Olympus <em>Control</em></h1><p>Readable competition operations with secure server-enforced authorization.</p></div><a className="secondary-action" href="/api/admin/export"><Download /> Export CSV</a></header>
    {notice && <div className="form-notice">{notice}</div>}
    <section className="metric-grid">{[["People",data.totals.people],["Solo",data.totals.solo],["Teams",data.totals.teams],["Approved",data.totals.verified],["Pending",data.totals.pending],["Submissions",data.totals.submissions],["Finalists",data.totals.finalists],["Remaining",Math.max(0,data.totals.capacity-data.totals.people)]].map(([label,value]) => <article className="glass-panel" key={label}><span>{label}</span><b>{value}</b></article>)}</section>
    <div className="admin-layout">
      <section className="admin-panel glass-panel"><div className="admin-panel-title"><UsersRound /><div><small>Participant management</small><h2>Realm entrants</h2></div></div><div className="admin-filters"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email or ID" /></label><select value={university} onChange={(event) => setUniversity(event.target.value)}><option value="">All universities</option>{universities.map((item) => <option key={item}>{item}</option>)}</select></div><div className="admin-table-wrap"><table><thead><tr><th>Participant</th><th>Type</th><th>Eligibility</th><th>Status</th><th>Action</th></tr></thead><tbody>{participants.map((person) => <tr key={person.id}><td><b>{person.name}</b><span>{person.code} · {person.university}</span></td><td>{person.type}</td><td><span className={`admin-state ${person.eligibility}`}>{person.eligibility}</span></td><td>{person.status.replaceAll("_", " ")}</td><td><div className="table-actions"><button disabled={busy} onClick={() => command({ action: "participant_status", participantId: person.id, eligibility: "eligible", status: "registered" })}>Approve</button><button disabled={busy} onClick={() => command({ action: "participant_status", participantId: person.id, eligibility: "rejected", status: "rejected" })}>Reject</button></div></td></tr>)}</tbody></table></div></section>
      <aside className="admin-side">
        <section className="admin-panel glass-panel"><div className="admin-panel-title"><Settings2 /><div><small>Dynamic states</small><h2>Competition</h2></div></div><div className="round-controls">{data.rounds.map((round) => <div key={round.id}><span><b>{round.name}</b><small>{round.status.replace("_", " ")}</small></span><select defaultValue={round.status} onChange={(event) => command({ action: "round_status", roundId: round.id, status: event.target.value, visibility: round.visibility })} disabled={busy}><option value="coming_soon">Coming soon</option><option value="open">Open</option><option value="closed">Closed</option><option value="completed">Complete</option></select></div>)}</div><div className="capacity-control field"><label htmlFor="capacity">Participant capacity</label><input id="capacity" type="number" min="1" max="100000" defaultValue={data.totals.capacity} onBlur={(event) => command({ action: "setting", key: "registration_capacity", value: Number(event.target.value) })} /></div></section>
        <section className="admin-panel glass-panel"><div className="admin-panel-title"><Megaphone /><div><small>Broadcast</small><h2>Announcement</h2></div></div><form className="announcement-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); command({ action: "announcement", title: form.get("title"), message: form.get("message"), priority: form.get("priority") }); }}><div className="field"><label htmlFor="announcementTitle">Title</label><input id="announcementTitle" name="title" required maxLength={150} /></div><div className="field"><label htmlFor="announcementMessage">Message</label><textarea id="announcementMessage" name="message" required maxLength={2000} /></div><div className="field"><label htmlFor="announcementPriority">Priority</label><select id="announcementPriority" name="priority"><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></div><button className="primary-action" disabled={busy}><ShieldCheck /> Publish</button></form></section>
        <section className="admin-panel glass-panel"><div className="admin-panel-title"><ScanLine /><div><small>Event entry</small><h2>Check-in</h2></div></div><form className="announcement-form" onSubmit={(event) => { event.preventDefault(); const value = String(new FormData(event.currentTarget).get("passToken") ?? "").replace(/^CRX3:/, "").trim(); command({ action: "checkin", passToken: value }); }}><div className="field"><label htmlFor="passToken">Scanned pass token</label><input id="passToken" name="passToken" required placeholder="CRX3:••••••••" /></div><button className="primary-action" disabled={busy}><ScanLine /> Verify entry</button></form></section>
      </aside>
    </div>
    <section className="admin-panel glass-panel university-panel"><div className="admin-panel-title"><span className="platform-kicker">Representation</span><h2>Universities</h2></div><div className="bar-chart">{data.universities.map((item) => <div key={item.name}><span>{item.name}</span><i><b style={{ width: `${Math.max(4,(item.count/Math.max(...data.universities.map((entry)=>entry.count),1))*100)}%` }} /></i><strong>{item.count}</strong></div>)}</div></section>
    <section className="admin-panel glass-panel university-panel"><div className="admin-panel-title"><UsersRound /><div><small>Alliance management</small><h2>Teams</h2></div></div><div className="admin-table-wrap"><table><thead><tr><th>Team</th><th>Invite code</th><th>Expected size</th><th>Status</th></tr></thead><tbody>{data.teams.map((team) => <tr key={team.id}><td><b>{team.name}</b></td><td>{team.code}</td><td>{team.expectedSize}</td><td><select value={team.status} disabled={busy} onChange={(event) => command({ action: "team_status", teamId: team.id, status: event.target.value })}><option value="active">Active</option><option value="approved">Approved</option><option value="locked">Locked</option><option value="rejected">Rejected</option><option value="disqualified">Disqualified</option></select></td></tr>)}</tbody></table></div></section>
  </div>;
}
